/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CityListItem: typeof import('./src/components/CityListItem.vue')['default']
    CityListItems: typeof import('./src/components/city-list-items.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SelectItemText: typeof import('reka-ui')['SelectItemText']
  }
}
